### PR TITLE
BERT as a Classifier Model Anjali Rani Pahal

### PR DESCRIPTION
**Pull request by asciarp08**

### CODE REVIEW

**Comment by IAmSuyogJadhav** [comment]
Be more specific and name your topic.

**Comment by asciarp08** [comment]
[BERT.docx](https://github.com/Cyber-Labs/Blog-Posts/files/3693541/BERT.docx)

**Comment by IAmSuyogJadhav** [comment]
@asciarp08, upload the article to the Machine Learning folder in your fork of this repo and rename to `BERT as a Classifier Model_Anjali`. Submit the PR afterwards.

**Comment by IAmSuyogJadhav** [comment]
Closing this one as another PR (#3) has already satisfied the purpose of this PR.

**Pull request closed without merging**
